---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
  - name: Print local
    hosts: localhost
    tasks:
      - name: Print fact1
        debug:
          msg: "{{ some_fact1 }}"